#!/bin/bash
#
# pipeline
#SBATCH -c 10
#SBATCH --mem 60g
#SBATCH --mail-type=ALL
# Assumes all of these tools are availble on the command line or using the conda environments provided

source ~/.bashrc

conda activate fusion_id

stringtie --merge -p 10 -o project_merged.gtf -G $PROJECT/data/genome/gencode/gencode.v34.primary_assembly.annotation.gtf $1
